version: '3'
services:
  mariadb:
    image: 'mariadb:10.3.8'
    container_name: 'b2bconnect_mariadb'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
  redis:
    image: 'redis:3.0.3'
    container_name: 'b2bconnect_redis'
    ports:
      - '6379:6379'
